[package]
name = "mcFail-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
craftping = { version = "0.7.0", features = ["tokio"] }
ipnet = "2.11.0"
tokio = { version = "1.47.1", features = ["net", "rt", "rt-multi-thread", "macros"] }
